export default {
    SET_PAGE_HEADER: 'SET_PAGE_HEADER',

    CREATE_MYAPI: 'CREATE_MYAPI',
    FETCH_MYAPI: 'FETCH_MYAPI',
    REMOVE_MYAPI: 'REMOVE_MYAPI',

    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT'
}