export default {
    SET_PAGE_HEADER: 'SET_PAGE_HEADER',

    CREATE_MYAPI: 'CREATE_MYAPI',
    FETCH_MYAPI: 'FETCH_MYAPI',
    REMOVE_MYAPI: 'REMOVE_MYAPI',
    CREATE_MYAPI_OK: 'CREATE_MYAPI_OK',
    FETCH_MYAPI_OK: 'FETCH_MYAPI_OK',
    REMOVE_MYAPI_OK: 'REMOVE_MYAPI_OK',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_OK: 'LOGIN_OK',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGOUT: 'LOGOUT',

    GET_USER_INFO: 'GET_USER_INFO',
    GET_USER_INFO_OK: 'GET_USER_INFO_OK',
    GET_USER_INFO_ERROR: 'GET_USER_INFO_ERROR',

}